### ISSUE TITLE
70B 학습 관련 에러 문의드립니다. 

### ISSUE THREAD

**Issue by Kyushik** [tabtoyou/KoLLaVA#9]
안녕하세요! 

진행해주신 프로젝트 덕분에 llava에 대해서 잘 공부해보고 있습니다! 감사합니다. 

현재 llama2-ko-7b와 llama2-13b에서는 레포에서 안내해주신 대로 qlora를 통해 학습 진행했을 때 에러 없이 학습이 잘 되고 있습니다. 
단 동일 환경에서 llama2-ko-70b나 llama2-70b를 사용하여 동일하게 qlora로 학습한 경우 shape 관련 에러가 발생하는 것을 확인했습니다. 

현재 진행중인 개발 환경은 다음과 같습니다. 
- ubuntu 20.04
- torch 2.0.1
- deepspeed 0.9.5
- accelerate 0.21.0
- transformers 4.31.0

이 경우 다음과 같이 model checkpoint 일부를 불러와서 초기화되는 문제가 있는 듯 합니다. 
<img width="706" alt="image" src="https://github.com/tabtoyou/KoLLaVA/assets/11716370/4217342c-ade2-47d0-8550-0a6bd79b0f64">

현재 발생한 에러 내용의 경우 다음과 같습니다. 
`Traceback (most recent call last):
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/train/train_mem.py", line 19, in <module>
    train()
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/train/train.py", line 911, in train
    trainer.train()
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/model/language_model/llava_llama.py", line 78, in forward
    outputs = self.model(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 685, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 681, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/train/llama_flash_attn_monkey_patch.py", line 41, in forward
    .view(bsz, q_len, self.num_heads, self.head_dim)
RuntimeError: shape '[4, 639, 64, 128]' is invalid for input of size 2617344
Traceback (most recent call last):
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/train/train_mem.py", line 19, in <module>
    train()
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/train/train.py", line 911, in train
    trainer.train()
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/model/language_model/llava_llama.py", line 78, in forward
    outputs = self.model(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 685, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 681, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/bc-user/.conda/envs/kollava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc-user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/di-LLM_458/queue.min/Study/KoLLaVA/llava/train/llama_flash_attn_monkey_patch.py", line 41, in forward
    .view(bsz, q_len, self.num_heads, self.head_dim)
RuntimeError: shape '[4, 806, 64, 128]' is invalid for input of size 3301376`

관련하여 내용 문의드립니다!
감사합니다!

**Comment by tabtoyou** [comment]
네 안녕하세요! 
KoLLaVA를 활용해 여러 시도를 해주셔서 감사합니다.

LLaMA-2 논문에 나와있듯이, 사이즈가 큰 34B, 70B 모델은 inference scalability를 위해 Grouped-Query Attention(GQA)를 사용했습니다. ("Bigger models — 34B and 70B — use Grouped-Query Attention (GQA) for improved inference scalability.")

하지만 현재 코드는 GQA가 반영되지 않아 위와 같은 shape 문제가 발생하는 것 같습니다.

아쉽게도 리소스 부족으로 현재는 GQA가 작동하도록 수정할 여력이 없네요.
LLaMA-2의 GQA [코드](https://github.com/huggingface/transformers/blob/e42587f596181396e1c4b63660abf0c736b10dae/src/transformers/models/llama/modeling_llama.py#L327)를 참고해 시도하시면 해결할 수 있을 것 같습니다.

감사합니다 :)

**Comment by Kyushik** [comment]
@tabtoyou 
아.. 사용하는 attention 방법 자체가 다르군요? GQA 작동할 수 있도록 수정을 해야되는 것이군요! 알겠습니다. 안내주셔서 감사합니다! 

그리고 추론 관련해서 질문이 하나 더 있습니다! #10 에서 질문 주신 내용과 연결될수도 있을 듯 합니다. 
우선 학습은 qlora 사용해서 진행했구요! merge_lora() 함수를 통해서 lora 모델을 hf 모델과 합쳐보려고 시도중입니다. 
제가 lora는 처음 사용해보고 있어서 이상한 질문일수도 있지만... 일단 qlora 통해서 학습했을 때 모델 저장했을 때 다음과 같은 파일들이 있는 것을 확인했습니다. 
<img width="624" alt="image" src="https://github.com/tabtoyou/KoLLaVA/assets/11716370/aaab7656-dd46-4390-80b8-387458b2d34d">

그리고 아래와 같이 model_path에는 qlora 모델 저장 경로, model_base에는 기반 모델로 사용한 llama-7b-ko의 경로로 작성을 했고 merge하는 코드를 간단하게 수행했습니다. 
```python 
model_path = "qlora 체크포인트 경로"
model_base = "llama 모델 경로"
save_model_path = "./save_test/"

def merge_lora():
    model_name = get_model_name_from_path(model_path)
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, model_base, model_name, device_map='cpu')

    model.save_pretrained(save_model_path)
    tokenizer.save_pretrained(save_model_path)

merge_lora()
```

이때 다음과 같이 model_path에 config.json이 없다는 에러가 발생하더라구요! 
<img width="607" alt="image" src="https://github.com/tabtoyou/KoLLaVA/assets/11716370/6a293673-0fa4-46f4-b740-31ca6c3c5022">

그래서 model_path가 llama 모델 경로인가..? 해서 수정해봤는데 그때는 #10 처럼 'LlamaForCausalLM' object has no attribute 'get_vision_tower' 에러가 발생했습니다. 이건 아마 llama 모델은 멀티모달이 아니어서 CLIP 모델이 사용되지 않아서 발생한 것 같고 뭔가 Llama 모델이 아니라 Llava 모델로 설정해야 인지해야 되는 것 같다.. 는 생각이었습니다. 
이에 따라 llama 모델과 학습한 llava qlora 모델을 통합해야 할 것 같아서 merge_lora를 실행해보려고 했습니다. 
하지만 어려움이 많네요 ㅜㅜㅜㅜㅜ 이에 따라 관련하여 질문 드립니다! 

감사합니다!

**Comment by Kyushik** [comment]
@tabtoyou 
그리고 추가로 하나만 더 질문드리자면 lora 사용에 위와 같은 문제가 있어서 7B 모델을 full finetuning을 해보려고 했으나 
zero2 사용시 아래와 같은 illegal memory access 문제가 발생했습니다. 
RuntimeError: CUDA error: an illegal memory access was encountered
해당 문제의 경우 memory 부족 등으로 발생하는 것으로 알고있는데 현재 A100 80G 2개 사용 중이고 batch size를 1로 해도 발생하는 것으로 봐서 메모리 문제는 아닌 것 같습니다. 

zero3 사용시에는 학습이 한 5 스텝 정도 진행되다가 아예 멈춰버리는 신기한 현상이 발생하고 있는 것 같습니다 ㅜㅜㅜ 

혹시 full finetuning으로도 진행해보셨을까요? 해당 경우에 이런 문제들이 없으셨는지도 함께 문의드립니다!

**Comment by tabtoyou** [comment]
1. config.json 에러

`kollava-llama-2-ko-7b-finetune-qlora2/checkpoint-500/` 디렉토리에 `config.json`을 만드시고, 아래 설정을 복붙한 후 다시 merge 해보시면 좋을 것 같습니다.

```
{
  "_name_or_path": "kfkas/Llama-2-ko-7b-Chat",
  "architectures": [
    "LlavaLlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "freeze_mm_mlp_adapter": false,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "image_aspect_ratio": "square",
  "image_grid_pinpoints": null,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_length": 4096,
  "max_position_embeddings": 2048,
  "mm_hidden_size": 1024,
  "mm_use_im_patch_token": false,
  "mm_use_im_start_end": false,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "mm_vision_tower": "openai/clip-vit-large-patch14",
  "model_type": "llava",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "quantization_config": {
    "bnb_4bit_compute_dtype": "bfloat16",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false
  },
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.31.0",
  "tune_mm_mlp_adapter": false,
  "use_cache": true,
  "use_mm_proj": true,
  "vocab_size": 46336
}
```

저도 해당 과정을 진행한 지 시간이 좀 되어 확실하지 않지만, 에러가 다시 발생하면 말씀해주세요.


2. 이전 버전에서는 full-finetuning이 잘 되었는데, 업데이트 후에는 qlora만 학습해보았습니다. 
LLaVA의 issues 에도 비슷한 에러가 올라온 것 같네요. https://github.com/haotian-liu/LLaVA/issues?q=is%3Aissue+is%3Aopen+illegal+memory+access 
해당 에러를 경험해보지 못해 해결방법은 모르겠지만, full-finetuning이 꼭 필요하시다면 이전 버전을 사용해보시는 것도 좋을 것 같습니다.

이전 버전 예시)
```
git clone https://github.com/tabtoyou/KoLLaVA.git
git reset --hard 263e78b1d843ee93825092fff8aa84eab793948f
```

**Comment by Kyushik** [comment]
아래와 같이 HFValidationError가 발생하는 것으로 보아 아마 lora의 checkpoint를 huggingface repo라고 인지하지 못하는 것 같습니다. 

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/di-LLM_458/queue.min/Study/KoLLaVA/checkpoints/kollava-llama-2-ko-7b-finetune_qlora2/checkpoint-500/'. Use `repo_type` argument if needed.

model_path에 lora 경로를 입력하는게 아닌가 싶기도 합니다. 제가 아직 LoRA, PEFT에 대한 이해가 적어서 잘 이해를 못하는 것 같아서 이쪽 공부를 좀더 해보겠습니다! 

항상 친절하게 답변주셔서 감사드립니다! :)

**Comment by tabtoyou** [comment]
네 지금 새로운 업데이트도 준비중인데요. 
merge나 web ui 등도 더 보완하겠습니다!
